use_frameworks!

target 'ScrollingPageControl_Example' do
  pod 'ScrollingPageControl', :git => 'https://github.com/HyunjoonKo/ScrollingPageControl.git', :branch => 'customized'

  target 'ScrollingPageControl_Tests' do
    inherit! :search_paths
  end
end
